export const queryKeys = {
  myProfile: ["users", "me"] as const,
  publicProfile: (username: string) => ["users", "public", username] as const,
  homeFeed: ["feed", "home"] as const,
  exploreFeed: (hashtag?: string) => ["feed", "explore", hashtag ?? null] as const,
  reelsFeed: ["feed", "reels"] as const,
  profileFeed: (username: string) => ["feed", "profile", username] as const,
  watchFeed: ["feed", "watch"] as const,
  relatedVideos: (slug: string) => ["feed", "related", slug] as const,
  post: (slug: string) => ["posts", slug] as const,
  userPosts: (username: string) => ["posts", "user", username] as const,
  comments: (slug: string) => ["comments", slug] as const,
  replies: (commentId: string) => ["replies", commentId] as const,
  savedPosts: ["posts", "saved"] as const,
  followers: (username: string) => ["follows", "followers", username] as const,
  following: (username: string) => ["follows", "following", username] as const,
  pendingFollowRequests: ["follows", "requests", "pending"] as const,
  blockedUsers: ["follows", "blocked"] as const,
  mutedUsers: ["follows", "muted"] as const,
  notifications: ["notifications"] as const,
  notificationUnreadCount: ["notifications", "unread-count"] as const,
  notificationPreferences: ["notifications", "preferences"] as const,
  conversations: ["messaging", "conversations"] as const,
  conversation: (id: string) => ["messaging", "conversations", id] as const,
  conversationMessages: (id: string) => ["messaging", "conversations", id, "messages"] as const,
  messagingUnreadCount: ["messaging", "unread-count"] as const,
  storyFeed: ["stories", "feed"] as const,
  userStories: (username: string) => ["stories", "user", username] as const,
  storyViewers: (storyId: string) => ["stories", storyId, "viewers"] as const,
  searchCombined: (q: string) => ["search", "combined", q] as const,
  searchUsers: (q: string) => ["search", "users", q] as const,
  searchHashtags: (q: string) => ["search", "hashtags", q] as const,
  searchPosts: (q: string) => ["search", "posts", q] as const,
  hashtagDetail: (name: string) => ["hashtags", name] as const,
  hashtagPosts: (name: string) => ["hashtags", name, "posts"] as const,
  trendingHashtags: ["hashtags", "trending"] as const,
  postMetrics: (slug: string, start: string, end: string) =>
    ["analytics", "post", slug, start, end] as const,
  userMetrics: (username: string, start: string, end: string) =>
    ["analytics", "user", username, start, end] as const,
  sessions: ["sessions"] as const,
  myDevices: ["devices"] as const,
  cryptoDevices: ["crypto", "devices"] as const,
} as const;